import '../models/performance_livestream_model.dart';

final List<TeachingPerformanceLiveStreamModel> performanceLivestreamList = [
  TeachingPerformanceLiveStreamModel(
    "assets/images/whats_bg.jpg",
    "10 Benefits of Cloud Computing and Why We Need To Learn",
    "18 May 2022 8:30pm",
    "5.7K",
    "21.5K",
    "3.5",
    "Alicia Yap",
  ),
  TeachingPerformanceLiveStreamModel(
    "assets/images/whats_bg.jpg",
    "11 Benefits of Cloud Computing and Why We Need To Learn",
    "18 May 2022 8:30pm",
    "5.7K",
    "21.5K",
    "4.5",
    "Alicia Yap",
  ),
  TeachingPerformanceLiveStreamModel(
    "assets/images/whats_bg.jpg",
    "11 Benefits of Cloud Computing and Why We Need To Learn",
    "18 May 2022 8:30pm",
    "5.7K",
    "21.5K",
    "4.0",
    "Alicia Yap",
  ),
  TeachingPerformanceLiveStreamModel(
    "assets/images/whats_bg.jpg",
    "11 Benefits of Cloud Computing and Why We Need To Learn",
    "18 May 2022 8:30pm",
    "5.7K",
    "21.5K",
    "4.0",
    "Alicia Yap",
  ),
  TeachingPerformanceLiveStreamModel(
    "assets/images/whats_bg.jpg",
    "11 Benefits of Cloud Computing and Why We Need To Learn",
    "18 May 2022 8:30pm",
    "5.7K",
    "21.5K",
    "4.0",
    "Alicia Yap",
  ),
  TeachingPerformanceLiveStreamModel(
    "assets/images/whats_bg.jpg",
    "11 Benefits of Cloud Computing and Why We Need To Learn",
    "18 May 2022 8:30pm",
    "5.7K",
    "21.5K",
    "4.0",
    "Alicia Yap",
  ),
  TeachingPerformanceLiveStreamModel(
    "assets/images/whats_bg.jpg",
    "11 Benefits of Cloud Computing and Why We Need To Learn",
    "18 May 2022 8:30pm",
    "5.7K",
    "21.5K",
    "4.0",
    "Alicia Yap",
  ),
  TeachingPerformanceLiveStreamModel(
    "assets/images/whats_bg.jpg",
    "10 Benefits of Cloud Computing and Why We Need To Learn",
    "18 May 2022 8:30pm",
    "5.7K",
    "21.5K",
    "4.0",
    "Alicia Yap",
  ),
  TeachingPerformanceLiveStreamModel(
    "assets/images/whats_bg.jpg",
    "10 Benefits of Cloud Computing and Why We Need To Learn",
    "18 May 2022 8:30pm",
    "5.7K",
    "21.5K",
    "4.0",
    "Alicia Yap",
  ),
  TeachingPerformanceLiveStreamModel(
    "assets/images/whats_bg.jpg",
    "10 Benefits of Cloud Computing and Why We Need To Learn",
    "18 May 2022 8:30pm",
    "5.7K",
    "21.5K",
    "4.0",
    "Alicia Yap",
  ),
];
