import '../models/schedule_livestream_model.dart';

final List<TeachingScheduleLiveStreamModel> liveStreamModelList = [
  TeachingScheduleLiveStreamModel(
      "MF000100 >",
      "Upcoming",
      "assets/images/whats_bg.jpg",
      "11 Benefits of Cloud Computing and Why We Need To Learn",
      "18 May 2022 8:30pm",
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Artificial Intelligence, Graphics Design, Digital Advertising, Creative Thinking",
      "Beginner",
      "English"),
  TeachingScheduleLiveStreamModel(
      "MF000100 >",
      "Ongoing",
      "assets/images/whats_bg.jpg",
      "12 Benefits of Cloud Computing and Why We Need To Learn",
      "18 May 2022 8:30pm",
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Artificial Intelligence, Graphics Design, Digital Advertising, Creative Thinking",
      "Beginner",
      "English"),
  TeachingScheduleLiveStreamModel(
      "MF000100 >",
      "Past",
      "assets/images/whats_bg.jpg",
      "13 Benefits of Cloud Computing and Why We Need To Learn",
      "18 May 2022 8:30pm",
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Artificial Intelligence, Graphics Design, Digital Advertising, Creative Thinking",
      "Beginner",
      "English"),
  TeachingScheduleLiveStreamModel(
      "MF000100 >",
      "Upcoming",
      "assets/images/whats_bg.jpg",
      "14 Benefits of Cloud Computing and Why We Need To Learn",
      "18 May 2022 8:30pm",
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Artificial Intelligence, Graphics Design, Digital Advertising, Creative Thinking",
      "Beginner",
      "English"),
  TeachingScheduleLiveStreamModel(
      "MF000100 >",
      "Ongoing",
      "assets/images/whats_bg.jpg",
      "15 Benefits of Cloud Computing and Why We Need To Learn",
      "18 May 2022 8:30pm",
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Artificial Intelligence, Graphics Design, Digital Advertising, Creative Thinking",
      "Beginner",
      "English"),
  TeachingScheduleLiveStreamModel(
      "MF000100 >",
      "Past",
      "assets/images/whats_bg.jpg",
      "16 Benefits of Cloud Computing and Why We Need To Learn",
      "18 May 2022 8:30pm",
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Artificial Intelligence, Graphics Design, Digital Advertising, Creative Thinking",
      "Beginner",
      "English"),
  TeachingScheduleLiveStreamModel(
      "MF000100 >",
      "Upcoming",
      "assets/images/whats_bg.jpg",
      "17 Benefits of Cloud Computing and Why We Need To Learn",
      "18 May 2022 8:30pm",
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Artificial Intelligence, Graphics Design, Digital Advertising, Creative Thinking",
      "Beginner",
      "English"),
  TeachingScheduleLiveStreamModel(
      "MF000100 >",
      "Ongoing",
      "assets/images/whats_bg.jpg",
      "18 Benefits of Cloud Computing and Why We Need To Learn",
      "18 May 2022 8:30pm",
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Artificial Intelligence, Graphics Design, Digital Advertising, Creative Thinking",
      "Beginner",
      "English"),
  TeachingScheduleLiveStreamModel(
      "MF000100 >",
      "Past",
      "assets/images/whats_bg.jpg",
      "19 Benefits of Cloud Computing and Why We Need To Learn",
      "18 May 2022 8:30pm",
      "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Artificial Intelligence, Graphics Design, Digital Advertising, Creative Thinking",
      "Beginner",
      "English"),
];
